#!/usr/bin/php
<?php

	namespace aidSQL;

	/**
	 * @todo Implement spl_autoload
	 * @todo Analyze script performance with xdebug
	 *
	 */

	set_include_path("lib/aidSQL/".PATH_SEPARATOR.get_include_path());

	define ("__CLASSPATH","lib/aidsql/class");

	error_reporting(E_ALL);

	function checkPHPVersion(){

		$version		= substr(PHP_VERSION,0,strpos(PHP_VERSION,"."));
		$subversion	= substr(PHP_VERSION,strpos(PHP_VERSION,".")+1);
		$subversion	= substr($subversion,0,strpos($subversion,"."));

		if($version != 5 || $subversion < 3){
			return FALSE;
			
		}

		return TRUE;

	}

	if(!checkPHPVersion()){

		echo "Sorry but you need at least version 5.3.0 in order to run aidSQL :(\n";
		exit(1);

	}

	//Interfaces
	require	"interface/Parser.interface.php";
	require	"interface/Log.interface.php";
	require	"interface/http/Adapter.interface.php";
	require	"interface/plugin/Injection.interface.php";
	require	"interface/plugin/Disclosure.interface.php";

	//Classes
	require	"class/core/String.class.php";
	require	"class/core/File.class.php";
	require	"class/core/Runner.class.php";
	require	"class/core/PluginLoader.class.php";
	require	"class/core/InjectionPlugin.class.php";
	require	"class/log/StdLog.class.php";
	require	"class/http/adapter/Ecurl.class.php";
	require	"class/http/crawler/Crowley.class.php";
	require	"class/http/webservice/bing/Bing.class.php";
	require	"class/http/webservice/google/Google.class.php";
	require	"config/config.php";
	
	//Parsers
	require	"class/parser/CmdLine.class.php";
	require	"class/parser/Nmap.class.php";

	//Functions
	require	"functions/launcher.functions.php";

	try {

		unset($_SERVER["argv"][0]);

		$sites			=	array();
		$links			=	array();

		$log	=	new Log\StdLog();
		$log->setEcho(TRUE);
		banner($log);
		$log->setPrepend("[aidSQL]");
		$parameters		=	mergeConfig($_SERVER["argv"],"etc/aidSQL.conf");
		$cmdParser		=	new parser\CmdLine($config,$parameters);
		$parsedOptions	=	$cmdParser->getParsedOptions();

		$log->setColors((bool)$parsedOptions["colors"]);


		if(isset($parsedOptions["log-save"])){
			$log->setFilename($parsedOptions["log-save"]);
		}


		if(!empty($parsedOptions["url"])){
			$sites[0]	=	$parsedOptions["url"]; 
		}

		//Instance of the http adapter, shared by aggregation through all classes

		$Adapter			=	"\\aidSQL\\http\\Adapter\\".$parsedOptions["http-adapter"];
		$httpAdapter	=	new $Adapter();
		$httpAdapter->setLog($log);
		
		if(isset($parsedOptions["connect-timeout"])){

			$httpAdapter->setConnectTimeout($parsedOptions["connect-timeout"]);

		}

		if(isset($parsedOptions["request-interval"])&&$parsedOptions["request-interval"]>0){
			$httpAdapter->setRequestInterval($parsedOptions["request-interval"]);
		}

		if(isset($parsedOptions["log-prepend-date"])){
			$log->useLogDate($parsedOptions["log-prepend-date"]);
		}

		//Check if youre bored and you just want to rule the world (?)
		/////////////////////////////////////////////////////////////////

		if(in_array("google",array_keys($parsedOptions))){

			$google	=	new aidsql\webservice\Google($httpAdapter,$log);
			$google->setQuery($parsedOptions["google"]);

			(isset($parsedOptions["google-language"])) ? $google->setLanguage($parsedOptions["google-language"]) : NULL;

			$offset		=	(isset($parsedOptions["google-offset"]))			? $parsedOptions["google-offset"] : 0;
			$userTotal	=	(isset($parsedOptions["google-max-results"]))	? $parsedOptions["google-max-results"] : 0;
			
			$sites = googleSearch($google,$offset,$userTotal);

			if(isset($parsedOptions["google-shuffle-sites"])){
				shuffle($sites);
			}

		}

		if(isset($parsedOptions["omit-sites"])){

			filterSites($sites,$log,$parsedOptions["omit-sites"]);

		}


		//Check if url vars where passed,if not, we crawl the url
		/////////////////////////////////////////////////////////////////

		if(!in_array("urlvars",array_keys($parsedOptions))){

			$httpAdapter->setMethod($parsedOptions["http-method"]);

			if(!sizeof($sites)){
				$log->log("No sites :(!",1,"red");
				exit(1);
			}

			foreach($sites as $site){

				$httpAdapter->setUrl($site);

				$crawlerName	=	"aidSQL\\http\\crawler\\$parsedOptions[crawler]";
				$crawler			=	new $crawlerName($httpAdapter,$log);

				if(isset($parsedOptions["lpp"])){

					$crawler->setLinksPerPage($parsedOptions["lpp"]);

				}

				if(isset($parsedOptions["max-links"])){

					$crawler->setMaxLinks($parsedOptions["max-links"]);

				}

				if(isset($parsedOptions["page-types"])){
					$crawler->addPageTypes(explode(",",$parsedOptions["page-types"]));
				}

				if(isset($parsedOptions["omit-paths"])){

					$omitPaths = explode(",",$parsedOptions["omit-paths"]);
					$crawler->addOmitPaths($omitPaths);

				}

				if(isset($parsedOptions["omit-pages"])){

					$omitPages = explode(",",$parsedOptions["omit-pages"]);
					$crawler->addOmitPages($omitPages);

				}

				$crawler->crawl();

				$links	=	$crawler->getLinks(TRUE);

				unset($crawler);

				//Takes away all crawled links without any parameters (useless to us ... to this date)
				filterLinksWithoutParameters($links);

				//Test crawled links
				testLinks($links,$httpAdapter,$cmdParser,$log);

			}


		}else{

			//If urlvars was specified we will do whatever the user tells us to do

			$links = array($parsedOptions["url"]=>$parsedOptions["urlvars"]);

		}

	}catch(\Exception $e){

		$log->log($e->getMessage(),1,"light_red");
		//echo $e->getTraceAsString()."\n";
		usageShort($log);

	}

	if(!sizeof($links)){

		$log->log("Not enough links / No valid links (i.e no parameters) to perform injection :(",1,"red");
		exit(1);

	}
	
	testLinks($links,$httpAdapter,$cmdParser,$log);
