#!/bin/sh

	dontHavePHP() {
		echo "\nYou dont seem to have PHP in your system, at least, not the command line version.";
		echo "If in a apt-get compatible Linux distribution this command: ";
		echo "\nsudo apt-get install php5-cli\n";
		echo "Remember that you must have at least PHP 5.3 to run aidSQL";
		echo "In case of having an apt based linux system you can read this article http://bit.ly/aB3XKe";
		echo "in order to update your system to PHP 5.3\n";
	}

	export PHP=$(which php);

	[ $? -eq 1 ] && dontHavePHP && exit 1;

	$PHP run/launcher.php $@
